<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>Firaw.SnapCopyText.Launcher</AssemblyName>
    <RootNamespace>Firaw.SnapCopyText.Launcher</RootNamespace>
    <ApplicationIcon>..\Firaw.SnapCopyText\Assets\firaw-eye.ico</ApplicationIcon>
    <Product>Firaw - SnapCopyText Launcher</Product>
    <Company>Firawynix</Company>
    <Version>1.1.14</Version>
    <AssemblyVersion>1.1.14.0</AssemblyVersion>
    <FileVersion>1.1.14.0</FileVersion>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>true</PublishTrimmed>
    <TrimMode>partial</TrimMode>
    <DebugType>none</DebugType>
  </PropertyGroup>
</Project>
