const api=window.snap,$=id=>document.getElementById(id);let imageUrl=null,drag=null,mode='region';
function setProgress(text,bad=false){$('progress').textContent=text;$('progress').classList.toggle('bad',bad)}
function enable(value){$('ocr').disabled=!value;$('copyImage').disabled=!value;$('save').disabled=!value}
async function capture(nextMode){mode=nextMode;$('sourceList').replaceChildren();$('canvas').style.display='none';enable(false);setProgress('Lendo as fontes de captura…');try{const sources=await api.sources(mode);for(const source of sources){const b=document.createElement('button');const img=document.createElement('img');img.src=source.thumbnail;const label=document.createElement('strong');label.textContent=source.name;b.append(img,label);b.onclick=()=>selectSource(source.thumbnail);$('sourceList').append(b)}setProgress(`${sources.length} fonte(s) encontrada(s).`)}catch(e){setProgress(e.message,true)}}
function selectSource(url){imageUrl=url;const img=new Image();img.onload=()=>{const canvas=$('canvas'),ctx=canvas.getContext('2d');canvas.width=img.naturalWidth;canvas.height=img.naturalHeight;ctx.drawImage(img,0,0);canvas.style.display='block';$('sourceList').replaceChildren();enable(true);setProgress(mode==='region'?'Arraste sobre a imagem para recortar uma região.':'Captura pronta.');};img.src=url}
function currentImage(){return imageUrl||$('canvas').toDataURL('image/png')}
function crop(start,end){const c=$('canvas'),rect=c.getBoundingClientRect(),sx=c.width/rect.width,sy=c.height/rect.height;const x=Math.max(0,Math.min(start.x,end.x)-rect.left)*sx,y=Math.max(0,Math.min(start.y,end.y)-rect.top)*sy,w=Math.abs(end.x-start.x)*sx,h=Math.abs(end.y-start.y)*sy;if(w<5||h<5)return;const out=document.createElement('canvas');out.width=Math.round(w);out.height=Math.round(h);out.getContext('2d').drawImage(c,x,y,w,h,0,0,w,h);imageUrl=out.toDataURL('image/png');selectSource(imageUrl)}
$('canvas').onpointerdown=e=>{if(mode==='region'){drag={x:e.clientX,y:e.clientY};$('canvas').setPointerCapture(e.pointerId)}};$('canvas').onpointerup=e=>{if(drag){crop(drag,{x:e.clientX,y:e.clientY});drag=null}};
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>capture(b.dataset.mode));
$('ocr').onclick=async()=>{try{setProgress('Preparando OCR local…');$('text').value=await api.ocr(currentImage());setProgress('Texto reconhecido.')}catch(e){setProgress(e.message,true)}};
$('copyImage').onclick=()=>api.copyImage(currentImage()).then(()=>setProgress('Imagem copiada.')).catch(e=>setProgress(e.message,true));
$('save').onclick=()=>api.save(currentImage()).then(file=>file&&setProgress(`Salvo em ${file}`)).catch(e=>setProgress(e.message,true));
$('copyText').onclick=()=>api.copyText($('text').value).then(()=>setProgress('Texto copiado.')).catch(e=>setProgress(e.message,true));
function renderHistory(items){$('history').replaceChildren(...items.map(text=>{const b=document.createElement('button');b.textContent=text;b.onclick=()=>{$('text').value=text};return b}))}api.onProgress(data=>setProgress(`${data.status||'OCR'} ${data.progress?Math.round(data.progress*100)+'%':''}`));api.onHistory(renderHistory);api.onRequest(next=>{if(next!=='none')capture(next)});api.history().then(renderHistory);capture('region');
